// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta_data.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "meta_data.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace MetaData {

namespace {

const ::google::protobuf::Descriptor* Box3DResult_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Box3DResult_reflection_ = NULL;
const ::google::protobuf::Descriptor* SensorFrame_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SensorFrame_reflection_ = NULL;
const ::google::protobuf::Descriptor* StructurePerception_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  StructurePerception_reflection_ = NULL;
const ::google::protobuf::Descriptor* Data_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Data_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_meta_5fdata_2eproto() {
  protobuf_AddDesc_meta_5fdata_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "meta_data.proto");
  GOOGLE_CHECK(file != NULL);
  Box3DResult_descriptor_ = file->message_type(0);
  static const int Box3DResult_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Box3DResult, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Box3DResult, box_),
  };
  Box3DResult_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Box3DResult_descriptor_,
      Box3DResult::default_instance_,
      Box3DResult_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Box3DResult, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Box3DResult, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Box3DResult));
  SensorFrame_descriptor_ = file->message_type(1);
  static const int SensorFrame_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SensorFrame, can_frames_raw_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SensorFrame, can_frames_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SensorFrame, imu_frames_raw_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SensorFrame, imu_frame_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SensorFrame, imu_offset_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SensorFrame, gps_frames_raw_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SensorFrame, gps_frame_),
  };
  SensorFrame_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SensorFrame_descriptor_,
      SensorFrame::default_instance_,
      SensorFrame_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SensorFrame, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SensorFrame, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SensorFrame));
  StructurePerception_descriptor_ = file->message_type(2);
  static const int StructurePerception_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StructurePerception, obstacles_raws_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StructurePerception, obstacles_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StructurePerception, lines_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StructurePerception, parsing_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StructurePerception, depth_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StructurePerception, scan_pts_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StructurePerception, parsing_settings_),
  };
  StructurePerception_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      StructurePerception_descriptor_,
      StructurePerception::default_instance_,
      StructurePerception_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StructurePerception, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(StructurePerception, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(StructurePerception));
  Data_descriptor_ = file->message_type(3);
  static const int Data_offsets_[11] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Data, version_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Data, frame_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Data, image_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Data, data_descriptor_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Data, camera_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Data, camera_default_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Data, camera_matrix_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Data, sensor_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Data, motion_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Data, odometry_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Data, structure_perception_),
  };
  Data_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Data_descriptor_,
      Data::default_instance_,
      Data_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Data, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Data, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Data));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_meta_5fdata_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Box3DResult_descriptor_, &Box3DResult::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SensorFrame_descriptor_, &SensorFrame::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    StructurePerception_descriptor_, &StructurePerception::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Data_descriptor_, &Data::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_meta_5fdata_2eproto() {
  delete Box3DResult::default_instance_;
  delete Box3DResult_reflection_;
  delete SensorFrame::default_instance_;
  delete SensorFrame_reflection_;
  delete StructurePerception::default_instance_;
  delete StructurePerception_reflection_;
  delete Data::default_instance_;
  delete Data_reflection_;
}

void protobuf_AddDesc_meta_5fdata_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::CommonProto::protobuf_AddDesc_common_2eproto();
  ::CANProto::protobuf_AddDesc_can_2eproto();
  ::SensorProto::protobuf_AddDesc_sensor_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017meta_data.proto\022\010MetaData\032\014common.prot"
    "o\032\tcan.proto\032\014sensor.proto\":\n\013Box3DResul"
    "t\022\n\n\002id\030\001 \002(\005\022\037\n\003box\030\002 \002(\0132\022.CommonProto"
    ".Box3D\"\304\002\n\013SensorFrame\022-\n\016can_frames_raw"
    "\030\001 \003(\0132\025.CANProto.CANFrameRaw\022&\n\ncan_fra"
    "mes\030\002 \001(\0132\022.CANProto.CANFrame\022-\n\016imu_fra"
    "mes_raw\030\013 \003(\0132\025.SensorProto.IMUFrame\022(\n\t"
    "imu_frame\030\014 \001(\0132\025.SensorProto.IMUFrame\022)"
    "\n\nimu_offset\030\r \001(\0132\025.SensorProto.IMUFram"
    "e\0220\n\016gps_frames_raw\030\025 \003(\0132\030.SensorProto."
    "GPSFrameRaw\022(\n\tgps_frame\030\026 \001(\0132\025.SensorP"
    "roto.GPSFrame\"\305\002\n\023StructurePerception\0221\n"
    "\016obstacles_raws\030\001 \003(\0132\031.CommonProto.Obst"
    "acleRaws\022)\n\tobstacles\030\n \003(\0132\026.CommonProt"
    "o.Obstacles\022!\n\005lines\030\013 \003(\0132\022.CommonProto"
    ".Lines\022#\n\007parsing\030\024 \003(\0132\022.CommonProto.Im"
    "age\022!\n\005depth\030\025 \003(\0132\022.CommonProto.Image\022."
    "\n\010scan_pts\030\036 \003(\0132\034.CommonProto.FreeSpace"
    "Points\0225\n\020parsing_settings\030( \003(\0132\033.Commo"
    "nProto.ParsingSetting\"\314\003\n\004Data\022\017\n\007versio"
    "n\030\001 \002(\005\022\020\n\010frame_id\030\002 \002(\005\022!\n\005image\030\003 \003(\013"
    "2\022.CommonProto.Image\0224\n\017data_descriptor\030"
    "\004 \003(\0132\033.CommonProto.DataDescriptor\022(\n\006ca"
    "mera\030\n \003(\0132\030.CommonProto.CameraParam\0220\n\016"
    "camera_default\030\013 \003(\0132\030.CommonProto.Camer"
    "aParam\0220\n\rcamera_matrix\030\014 \003(\0132\031.CommonPr"
    "oto.CameraMatrix\022%\n\006sensor\030\024 \001(\0132\025.MetaD"
    "ata.SensorFrame\022(\n\006motion\030\025 \001(\0132\030.Common"
    "Proto.MotionFrame\022,\n\010odometry\030\026 \001(\0132\032.Co"
    "mmonProto.OdometryFrame\022;\n\024structure_per"
    "ception\030\036 \001(\0132\035.MetaData.StructurePercep"
    "tion", 1244);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "meta_data.proto", &protobuf_RegisterTypes);
  Box3DResult::default_instance_ = new Box3DResult();
  SensorFrame::default_instance_ = new SensorFrame();
  StructurePerception::default_instance_ = new StructurePerception();
  Data::default_instance_ = new Data();
  Box3DResult::default_instance_->InitAsDefaultInstance();
  SensorFrame::default_instance_->InitAsDefaultInstance();
  StructurePerception::default_instance_->InitAsDefaultInstance();
  Data::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_meta_5fdata_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_meta_5fdata_2eproto {
  StaticDescriptorInitializer_meta_5fdata_2eproto() {
    protobuf_AddDesc_meta_5fdata_2eproto();
  }
} static_descriptor_initializer_meta_5fdata_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Box3DResult::kIdFieldNumber;
const int Box3DResult::kBoxFieldNumber;
#endif  // !_MSC_VER

Box3DResult::Box3DResult()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MetaData.Box3DResult)
}

void Box3DResult::InitAsDefaultInstance() {
  box_ = const_cast< ::CommonProto::Box3D*>(&::CommonProto::Box3D::default_instance());
}

Box3DResult::Box3DResult(const Box3DResult& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MetaData.Box3DResult)
}

void Box3DResult::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0;
  box_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Box3DResult::~Box3DResult() {
  // @@protoc_insertion_point(destructor:MetaData.Box3DResult)
  SharedDtor();
}

void Box3DResult::SharedDtor() {
  if (this != default_instance_) {
    delete box_;
  }
}

void Box3DResult::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Box3DResult::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Box3DResult_descriptor_;
}

const Box3DResult& Box3DResult::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_meta_5fdata_2eproto();
  return *default_instance_;
}

Box3DResult* Box3DResult::default_instance_ = NULL;

Box3DResult* Box3DResult::New() const {
  return new Box3DResult;
}

void Box3DResult::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    id_ = 0;
    if (has_box()) {
      if (box_ != NULL) box_->::CommonProto::Box3D::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Box3DResult::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MetaData.Box3DResult)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_box;
        break;
      }

      // required .CommonProto.Box3D box = 2;
      case 2: {
        if (tag == 18) {
         parse_box:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_box()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MetaData.Box3DResult)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MetaData.Box3DResult)
  return false;
#undef DO_
}

void Box3DResult::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MetaData.Box3DResult)
  // required int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // required .CommonProto.Box3D box = 2;
  if (has_box()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->box(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MetaData.Box3DResult)
}

::google::protobuf::uint8* Box3DResult::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MetaData.Box3DResult)
  // required int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // required .CommonProto.Box3D box = 2;
  if (has_box()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->box(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MetaData.Box3DResult)
  return target;
}

int Box3DResult::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // required .CommonProto.Box3D box = 2;
    if (has_box()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->box());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Box3DResult::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Box3DResult* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Box3DResult*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Box3DResult::MergeFrom(const Box3DResult& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_box()) {
      mutable_box()->::CommonProto::Box3D::MergeFrom(from.box());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Box3DResult::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Box3DResult::CopyFrom(const Box3DResult& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Box3DResult::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_box()) {
    if (!this->box().IsInitialized()) return false;
  }
  return true;
}

void Box3DResult::Swap(Box3DResult* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(box_, other->box_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Box3DResult::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Box3DResult_descriptor_;
  metadata.reflection = Box3DResult_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int SensorFrame::kCanFramesRawFieldNumber;
const int SensorFrame::kCanFramesFieldNumber;
const int SensorFrame::kImuFramesRawFieldNumber;
const int SensorFrame::kImuFrameFieldNumber;
const int SensorFrame::kImuOffsetFieldNumber;
const int SensorFrame::kGpsFramesRawFieldNumber;
const int SensorFrame::kGpsFrameFieldNumber;
#endif  // !_MSC_VER

SensorFrame::SensorFrame()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MetaData.SensorFrame)
}

void SensorFrame::InitAsDefaultInstance() {
  can_frames_ = const_cast< ::CANProto::CANFrame*>(&::CANProto::CANFrame::default_instance());
  imu_frame_ = const_cast< ::SensorProto::IMUFrame*>(&::SensorProto::IMUFrame::default_instance());
  imu_offset_ = const_cast< ::SensorProto::IMUFrame*>(&::SensorProto::IMUFrame::default_instance());
  gps_frame_ = const_cast< ::SensorProto::GPSFrame*>(&::SensorProto::GPSFrame::default_instance());
}

SensorFrame::SensorFrame(const SensorFrame& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MetaData.SensorFrame)
}

void SensorFrame::SharedCtor() {
  _cached_size_ = 0;
  can_frames_ = NULL;
  imu_frame_ = NULL;
  imu_offset_ = NULL;
  gps_frame_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SensorFrame::~SensorFrame() {
  // @@protoc_insertion_point(destructor:MetaData.SensorFrame)
  SharedDtor();
}

void SensorFrame::SharedDtor() {
  if (this != default_instance_) {
    delete can_frames_;
    delete imu_frame_;
    delete imu_offset_;
    delete gps_frame_;
  }
}

void SensorFrame::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SensorFrame::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SensorFrame_descriptor_;
}

const SensorFrame& SensorFrame::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_meta_5fdata_2eproto();
  return *default_instance_;
}

SensorFrame* SensorFrame::default_instance_ = NULL;

SensorFrame* SensorFrame::New() const {
  return new SensorFrame;
}

void SensorFrame::Clear() {
  if (_has_bits_[0 / 32] & 90) {
    if (has_can_frames()) {
      if (can_frames_ != NULL) can_frames_->::CANProto::CANFrame::Clear();
    }
    if (has_imu_frame()) {
      if (imu_frame_ != NULL) imu_frame_->::SensorProto::IMUFrame::Clear();
    }
    if (has_imu_offset()) {
      if (imu_offset_ != NULL) imu_offset_->::SensorProto::IMUFrame::Clear();
    }
    if (has_gps_frame()) {
      if (gps_frame_ != NULL) gps_frame_->::SensorProto::GPSFrame::Clear();
    }
  }
  can_frames_raw_.Clear();
  imu_frames_raw_.Clear();
  gps_frames_raw_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SensorFrame::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MetaData.SensorFrame)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(16383);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .CANProto.CANFrameRaw can_frames_raw = 1;
      case 1: {
        if (tag == 10) {
         parse_can_frames_raw:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_can_frames_raw()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_can_frames_raw;
        if (input->ExpectTag(18)) goto parse_can_frames;
        break;
      }

      // optional .CANProto.CANFrame can_frames = 2;
      case 2: {
        if (tag == 18) {
         parse_can_frames:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_can_frames()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(90)) goto parse_imu_frames_raw;
        break;
      }

      // repeated .SensorProto.IMUFrame imu_frames_raw = 11;
      case 11: {
        if (tag == 90) {
         parse_imu_frames_raw:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_imu_frames_raw()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(90)) goto parse_imu_frames_raw;
        if (input->ExpectTag(98)) goto parse_imu_frame;
        break;
      }

      // optional .SensorProto.IMUFrame imu_frame = 12;
      case 12: {
        if (tag == 98) {
         parse_imu_frame:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_imu_frame()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(106)) goto parse_imu_offset;
        break;
      }

      // optional .SensorProto.IMUFrame imu_offset = 13;
      case 13: {
        if (tag == 106) {
         parse_imu_offset:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_imu_offset()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(170)) goto parse_gps_frames_raw;
        break;
      }

      // repeated .SensorProto.GPSFrameRaw gps_frames_raw = 21;
      case 21: {
        if (tag == 170) {
         parse_gps_frames_raw:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_gps_frames_raw()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(170)) goto parse_gps_frames_raw;
        if (input->ExpectTag(178)) goto parse_gps_frame;
        break;
      }

      // optional .SensorProto.GPSFrame gps_frame = 22;
      case 22: {
        if (tag == 178) {
         parse_gps_frame:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_gps_frame()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MetaData.SensorFrame)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MetaData.SensorFrame)
  return false;
#undef DO_
}

void SensorFrame::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MetaData.SensorFrame)
  // repeated .CANProto.CANFrameRaw can_frames_raw = 1;
  for (int i = 0; i < this->can_frames_raw_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->can_frames_raw(i), output);
  }

  // optional .CANProto.CANFrame can_frames = 2;
  if (has_can_frames()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->can_frames(), output);
  }

  // repeated .SensorProto.IMUFrame imu_frames_raw = 11;
  for (int i = 0; i < this->imu_frames_raw_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, this->imu_frames_raw(i), output);
  }

  // optional .SensorProto.IMUFrame imu_frame = 12;
  if (has_imu_frame()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      12, this->imu_frame(), output);
  }

  // optional .SensorProto.IMUFrame imu_offset = 13;
  if (has_imu_offset()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      13, this->imu_offset(), output);
  }

  // repeated .SensorProto.GPSFrameRaw gps_frames_raw = 21;
  for (int i = 0; i < this->gps_frames_raw_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      21, this->gps_frames_raw(i), output);
  }

  // optional .SensorProto.GPSFrame gps_frame = 22;
  if (has_gps_frame()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      22, this->gps_frame(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MetaData.SensorFrame)
}

::google::protobuf::uint8* SensorFrame::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MetaData.SensorFrame)
  // repeated .CANProto.CANFrameRaw can_frames_raw = 1;
  for (int i = 0; i < this->can_frames_raw_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->can_frames_raw(i), target);
  }

  // optional .CANProto.CANFrame can_frames = 2;
  if (has_can_frames()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->can_frames(), target);
  }

  // repeated .SensorProto.IMUFrame imu_frames_raw = 11;
  for (int i = 0; i < this->imu_frames_raw_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        11, this->imu_frames_raw(i), target);
  }

  // optional .SensorProto.IMUFrame imu_frame = 12;
  if (has_imu_frame()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        12, this->imu_frame(), target);
  }

  // optional .SensorProto.IMUFrame imu_offset = 13;
  if (has_imu_offset()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        13, this->imu_offset(), target);
  }

  // repeated .SensorProto.GPSFrameRaw gps_frames_raw = 21;
  for (int i = 0; i < this->gps_frames_raw_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        21, this->gps_frames_raw(i), target);
  }

  // optional .SensorProto.GPSFrame gps_frame = 22;
  if (has_gps_frame()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        22, this->gps_frame(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MetaData.SensorFrame)
  return target;
}

int SensorFrame::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    // optional .CANProto.CANFrame can_frames = 2;
    if (has_can_frames()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->can_frames());
    }

    // optional .SensorProto.IMUFrame imu_frame = 12;
    if (has_imu_frame()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->imu_frame());
    }

    // optional .SensorProto.IMUFrame imu_offset = 13;
    if (has_imu_offset()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->imu_offset());
    }

    // optional .SensorProto.GPSFrame gps_frame = 22;
    if (has_gps_frame()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->gps_frame());
    }

  }
  // repeated .CANProto.CANFrameRaw can_frames_raw = 1;
  total_size += 1 * this->can_frames_raw_size();
  for (int i = 0; i < this->can_frames_raw_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->can_frames_raw(i));
  }

  // repeated .SensorProto.IMUFrame imu_frames_raw = 11;
  total_size += 1 * this->imu_frames_raw_size();
  for (int i = 0; i < this->imu_frames_raw_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->imu_frames_raw(i));
  }

  // repeated .SensorProto.GPSFrameRaw gps_frames_raw = 21;
  total_size += 2 * this->gps_frames_raw_size();
  for (int i = 0; i < this->gps_frames_raw_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->gps_frames_raw(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SensorFrame::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SensorFrame* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SensorFrame*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SensorFrame::MergeFrom(const SensorFrame& from) {
  GOOGLE_CHECK_NE(&from, this);
  can_frames_raw_.MergeFrom(from.can_frames_raw_);
  imu_frames_raw_.MergeFrom(from.imu_frames_raw_);
  gps_frames_raw_.MergeFrom(from.gps_frames_raw_);
  if (from._has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    if (from.has_can_frames()) {
      mutable_can_frames()->::CANProto::CANFrame::MergeFrom(from.can_frames());
    }
    if (from.has_imu_frame()) {
      mutable_imu_frame()->::SensorProto::IMUFrame::MergeFrom(from.imu_frame());
    }
    if (from.has_imu_offset()) {
      mutable_imu_offset()->::SensorProto::IMUFrame::MergeFrom(from.imu_offset());
    }
    if (from.has_gps_frame()) {
      mutable_gps_frame()->::SensorProto::GPSFrame::MergeFrom(from.gps_frame());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SensorFrame::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SensorFrame::CopyFrom(const SensorFrame& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SensorFrame::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->can_frames_raw())) return false;
  if (has_can_frames()) {
    if (!this->can_frames().IsInitialized()) return false;
  }
  if (!::google::protobuf::internal::AllAreInitialized(this->imu_frames_raw())) return false;
  if (has_imu_frame()) {
    if (!this->imu_frame().IsInitialized()) return false;
  }
  if (has_imu_offset()) {
    if (!this->imu_offset().IsInitialized()) return false;
  }
  if (!::google::protobuf::internal::AllAreInitialized(this->gps_frames_raw())) return false;
  if (has_gps_frame()) {
    if (!this->gps_frame().IsInitialized()) return false;
  }
  return true;
}

void SensorFrame::Swap(SensorFrame* other) {
  if (other != this) {
    can_frames_raw_.Swap(&other->can_frames_raw_);
    std::swap(can_frames_, other->can_frames_);
    imu_frames_raw_.Swap(&other->imu_frames_raw_);
    std::swap(imu_frame_, other->imu_frame_);
    std::swap(imu_offset_, other->imu_offset_);
    gps_frames_raw_.Swap(&other->gps_frames_raw_);
    std::swap(gps_frame_, other->gps_frame_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SensorFrame::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SensorFrame_descriptor_;
  metadata.reflection = SensorFrame_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int StructurePerception::kObstaclesRawsFieldNumber;
const int StructurePerception::kObstaclesFieldNumber;
const int StructurePerception::kLinesFieldNumber;
const int StructurePerception::kParsingFieldNumber;
const int StructurePerception::kDepthFieldNumber;
const int StructurePerception::kScanPtsFieldNumber;
const int StructurePerception::kParsingSettingsFieldNumber;
#endif  // !_MSC_VER

StructurePerception::StructurePerception()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MetaData.StructurePerception)
}

void StructurePerception::InitAsDefaultInstance() {
}

StructurePerception::StructurePerception(const StructurePerception& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MetaData.StructurePerception)
}

void StructurePerception::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

StructurePerception::~StructurePerception() {
  // @@protoc_insertion_point(destructor:MetaData.StructurePerception)
  SharedDtor();
}

void StructurePerception::SharedDtor() {
  if (this != default_instance_) {
  }
}

void StructurePerception::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* StructurePerception::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return StructurePerception_descriptor_;
}

const StructurePerception& StructurePerception::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_meta_5fdata_2eproto();
  return *default_instance_;
}

StructurePerception* StructurePerception::default_instance_ = NULL;

StructurePerception* StructurePerception::New() const {
  return new StructurePerception;
}

void StructurePerception::Clear() {
  obstacles_raws_.Clear();
  obstacles_.Clear();
  lines_.Clear();
  parsing_.Clear();
  depth_.Clear();
  scan_pts_.Clear();
  parsing_settings_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool StructurePerception::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MetaData.StructurePerception)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(16383);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .CommonProto.ObstacleRaws obstacles_raws = 1;
      case 1: {
        if (tag == 10) {
         parse_obstacles_raws:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_obstacles_raws()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_obstacles_raws;
        if (input->ExpectTag(82)) goto parse_obstacles;
        break;
      }

      // repeated .CommonProto.Obstacles obstacles = 10;
      case 10: {
        if (tag == 82) {
         parse_obstacles:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_obstacles()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(82)) goto parse_obstacles;
        if (input->ExpectTag(90)) goto parse_lines;
        break;
      }

      // repeated .CommonProto.Lines lines = 11;
      case 11: {
        if (tag == 90) {
         parse_lines:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_lines()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(90)) goto parse_lines;
        if (input->ExpectTag(162)) goto parse_parsing;
        break;
      }

      // repeated .CommonProto.Image parsing = 20;
      case 20: {
        if (tag == 162) {
         parse_parsing:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_parsing()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(162)) goto parse_parsing;
        if (input->ExpectTag(170)) goto parse_depth;
        break;
      }

      // repeated .CommonProto.Image depth = 21;
      case 21: {
        if (tag == 170) {
         parse_depth:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_depth()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(170)) goto parse_depth;
        if (input->ExpectTag(242)) goto parse_scan_pts;
        break;
      }

      // repeated .CommonProto.FreeSpacePoints scan_pts = 30;
      case 30: {
        if (tag == 242) {
         parse_scan_pts:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_scan_pts()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(242)) goto parse_scan_pts;
        if (input->ExpectTag(322)) goto parse_parsing_settings;
        break;
      }

      // repeated .CommonProto.ParsingSetting parsing_settings = 40;
      case 40: {
        if (tag == 322) {
         parse_parsing_settings:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_parsing_settings()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(322)) goto parse_parsing_settings;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MetaData.StructurePerception)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MetaData.StructurePerception)
  return false;
#undef DO_
}

void StructurePerception::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MetaData.StructurePerception)
  // repeated .CommonProto.ObstacleRaws obstacles_raws = 1;
  for (int i = 0; i < this->obstacles_raws_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->obstacles_raws(i), output);
  }

  // repeated .CommonProto.Obstacles obstacles = 10;
  for (int i = 0; i < this->obstacles_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      10, this->obstacles(i), output);
  }

  // repeated .CommonProto.Lines lines = 11;
  for (int i = 0; i < this->lines_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, this->lines(i), output);
  }

  // repeated .CommonProto.Image parsing = 20;
  for (int i = 0; i < this->parsing_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      20, this->parsing(i), output);
  }

  // repeated .CommonProto.Image depth = 21;
  for (int i = 0; i < this->depth_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      21, this->depth(i), output);
  }

  // repeated .CommonProto.FreeSpacePoints scan_pts = 30;
  for (int i = 0; i < this->scan_pts_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      30, this->scan_pts(i), output);
  }

  // repeated .CommonProto.ParsingSetting parsing_settings = 40;
  for (int i = 0; i < this->parsing_settings_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      40, this->parsing_settings(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MetaData.StructurePerception)
}

::google::protobuf::uint8* StructurePerception::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MetaData.StructurePerception)
  // repeated .CommonProto.ObstacleRaws obstacles_raws = 1;
  for (int i = 0; i < this->obstacles_raws_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->obstacles_raws(i), target);
  }

  // repeated .CommonProto.Obstacles obstacles = 10;
  for (int i = 0; i < this->obstacles_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        10, this->obstacles(i), target);
  }

  // repeated .CommonProto.Lines lines = 11;
  for (int i = 0; i < this->lines_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        11, this->lines(i), target);
  }

  // repeated .CommonProto.Image parsing = 20;
  for (int i = 0; i < this->parsing_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        20, this->parsing(i), target);
  }

  // repeated .CommonProto.Image depth = 21;
  for (int i = 0; i < this->depth_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        21, this->depth(i), target);
  }

  // repeated .CommonProto.FreeSpacePoints scan_pts = 30;
  for (int i = 0; i < this->scan_pts_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        30, this->scan_pts(i), target);
  }

  // repeated .CommonProto.ParsingSetting parsing_settings = 40;
  for (int i = 0; i < this->parsing_settings_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        40, this->parsing_settings(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MetaData.StructurePerception)
  return target;
}

int StructurePerception::ByteSize() const {
  int total_size = 0;

  // repeated .CommonProto.ObstacleRaws obstacles_raws = 1;
  total_size += 1 * this->obstacles_raws_size();
  for (int i = 0; i < this->obstacles_raws_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->obstacles_raws(i));
  }

  // repeated .CommonProto.Obstacles obstacles = 10;
  total_size += 1 * this->obstacles_size();
  for (int i = 0; i < this->obstacles_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->obstacles(i));
  }

  // repeated .CommonProto.Lines lines = 11;
  total_size += 1 * this->lines_size();
  for (int i = 0; i < this->lines_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->lines(i));
  }

  // repeated .CommonProto.Image parsing = 20;
  total_size += 2 * this->parsing_size();
  for (int i = 0; i < this->parsing_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->parsing(i));
  }

  // repeated .CommonProto.Image depth = 21;
  total_size += 2 * this->depth_size();
  for (int i = 0; i < this->depth_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->depth(i));
  }

  // repeated .CommonProto.FreeSpacePoints scan_pts = 30;
  total_size += 2 * this->scan_pts_size();
  for (int i = 0; i < this->scan_pts_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->scan_pts(i));
  }

  // repeated .CommonProto.ParsingSetting parsing_settings = 40;
  total_size += 2 * this->parsing_settings_size();
  for (int i = 0; i < this->parsing_settings_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->parsing_settings(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void StructurePerception::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const StructurePerception* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const StructurePerception*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void StructurePerception::MergeFrom(const StructurePerception& from) {
  GOOGLE_CHECK_NE(&from, this);
  obstacles_raws_.MergeFrom(from.obstacles_raws_);
  obstacles_.MergeFrom(from.obstacles_);
  lines_.MergeFrom(from.lines_);
  parsing_.MergeFrom(from.parsing_);
  depth_.MergeFrom(from.depth_);
  scan_pts_.MergeFrom(from.scan_pts_);
  parsing_settings_.MergeFrom(from.parsing_settings_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void StructurePerception::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StructurePerception::CopyFrom(const StructurePerception& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StructurePerception::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->obstacles_raws())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->obstacles())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->lines())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->parsing())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->depth())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->scan_pts())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->parsing_settings())) return false;
  return true;
}

void StructurePerception::Swap(StructurePerception* other) {
  if (other != this) {
    obstacles_raws_.Swap(&other->obstacles_raws_);
    obstacles_.Swap(&other->obstacles_);
    lines_.Swap(&other->lines_);
    parsing_.Swap(&other->parsing_);
    depth_.Swap(&other->depth_);
    scan_pts_.Swap(&other->scan_pts_);
    parsing_settings_.Swap(&other->parsing_settings_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata StructurePerception::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = StructurePerception_descriptor_;
  metadata.reflection = StructurePerception_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Data::kVersionFieldNumber;
const int Data::kFrameIdFieldNumber;
const int Data::kImageFieldNumber;
const int Data::kDataDescriptorFieldNumber;
const int Data::kCameraFieldNumber;
const int Data::kCameraDefaultFieldNumber;
const int Data::kCameraMatrixFieldNumber;
const int Data::kSensorFieldNumber;
const int Data::kMotionFieldNumber;
const int Data::kOdometryFieldNumber;
const int Data::kStructurePerceptionFieldNumber;
#endif  // !_MSC_VER

Data::Data()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MetaData.Data)
}

void Data::InitAsDefaultInstance() {
  sensor_ = const_cast< ::MetaData::SensorFrame*>(&::MetaData::SensorFrame::default_instance());
  motion_ = const_cast< ::CommonProto::MotionFrame*>(&::CommonProto::MotionFrame::default_instance());
  odometry_ = const_cast< ::CommonProto::OdometryFrame*>(&::CommonProto::OdometryFrame::default_instance());
  structure_perception_ = const_cast< ::MetaData::StructurePerception*>(&::MetaData::StructurePerception::default_instance());
}

Data::Data(const Data& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MetaData.Data)
}

void Data::SharedCtor() {
  _cached_size_ = 0;
  version_ = 0;
  frame_id_ = 0;
  sensor_ = NULL;
  motion_ = NULL;
  odometry_ = NULL;
  structure_perception_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Data::~Data() {
  // @@protoc_insertion_point(destructor:MetaData.Data)
  SharedDtor();
}

void Data::SharedDtor() {
  if (this != default_instance_) {
    delete sensor_;
    delete motion_;
    delete odometry_;
    delete structure_perception_;
  }
}

void Data::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Data::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Data_descriptor_;
}

const Data& Data::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_meta_5fdata_2eproto();
  return *default_instance_;
}

Data* Data::default_instance_ = NULL;

Data* Data::New() const {
  return new Data;
}

void Data::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<Data*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 131) {
    ZR_(version_, frame_id_);
    if (has_sensor()) {
      if (sensor_ != NULL) sensor_->::MetaData::SensorFrame::Clear();
    }
  }
  if (_has_bits_[8 / 32] & 1792) {
    if (has_motion()) {
      if (motion_ != NULL) motion_->::CommonProto::MotionFrame::Clear();
    }
    if (has_odometry()) {
      if (odometry_ != NULL) odometry_->::CommonProto::OdometryFrame::Clear();
    }
    if (has_structure_perception()) {
      if (structure_perception_ != NULL) structure_perception_->::MetaData::StructurePerception::Clear();
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  image_.Clear();
  data_descriptor_.Clear();
  camera_.Clear();
  camera_default_.Clear();
  camera_matrix_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Data::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MetaData.Data)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(16383);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 version = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &version_)));
          set_has_version();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_frame_id;
        break;
      }

      // required int32 frame_id = 2;
      case 2: {
        if (tag == 16) {
         parse_frame_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &frame_id_)));
          set_has_frame_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_image;
        break;
      }

      // repeated .CommonProto.Image image = 3;
      case 3: {
        if (tag == 26) {
         parse_image:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_image()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_image;
        if (input->ExpectTag(34)) goto parse_data_descriptor;
        break;
      }

      // repeated .CommonProto.DataDescriptor data_descriptor = 4;
      case 4: {
        if (tag == 34) {
         parse_data_descriptor:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_data_descriptor()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_data_descriptor;
        if (input->ExpectTag(82)) goto parse_camera;
        break;
      }

      // repeated .CommonProto.CameraParam camera = 10;
      case 10: {
        if (tag == 82) {
         parse_camera:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_camera()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(82)) goto parse_camera;
        if (input->ExpectTag(90)) goto parse_camera_default;
        break;
      }

      // repeated .CommonProto.CameraParam camera_default = 11;
      case 11: {
        if (tag == 90) {
         parse_camera_default:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_camera_default()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(90)) goto parse_camera_default;
        if (input->ExpectTag(98)) goto parse_camera_matrix;
        break;
      }

      // repeated .CommonProto.CameraMatrix camera_matrix = 12;
      case 12: {
        if (tag == 98) {
         parse_camera_matrix:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_camera_matrix()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(98)) goto parse_camera_matrix;
        if (input->ExpectTag(162)) goto parse_sensor;
        break;
      }

      // optional .MetaData.SensorFrame sensor = 20;
      case 20: {
        if (tag == 162) {
         parse_sensor:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_sensor()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(170)) goto parse_motion;
        break;
      }

      // optional .CommonProto.MotionFrame motion = 21;
      case 21: {
        if (tag == 170) {
         parse_motion:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_motion()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(178)) goto parse_odometry;
        break;
      }

      // optional .CommonProto.OdometryFrame odometry = 22;
      case 22: {
        if (tag == 178) {
         parse_odometry:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_odometry()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(242)) goto parse_structure_perception;
        break;
      }

      // optional .MetaData.StructurePerception structure_perception = 30;
      case 30: {
        if (tag == 242) {
         parse_structure_perception:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_structure_perception()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MetaData.Data)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MetaData.Data)
  return false;
#undef DO_
}

void Data::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MetaData.Data)
  // required int32 version = 1;
  if (has_version()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->version(), output);
  }

  // required int32 frame_id = 2;
  if (has_frame_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->frame_id(), output);
  }

  // repeated .CommonProto.Image image = 3;
  for (int i = 0; i < this->image_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->image(i), output);
  }

  // repeated .CommonProto.DataDescriptor data_descriptor = 4;
  for (int i = 0; i < this->data_descriptor_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->data_descriptor(i), output);
  }

  // repeated .CommonProto.CameraParam camera = 10;
  for (int i = 0; i < this->camera_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      10, this->camera(i), output);
  }

  // repeated .CommonProto.CameraParam camera_default = 11;
  for (int i = 0; i < this->camera_default_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, this->camera_default(i), output);
  }

  // repeated .CommonProto.CameraMatrix camera_matrix = 12;
  for (int i = 0; i < this->camera_matrix_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      12, this->camera_matrix(i), output);
  }

  // optional .MetaData.SensorFrame sensor = 20;
  if (has_sensor()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      20, this->sensor(), output);
  }

  // optional .CommonProto.MotionFrame motion = 21;
  if (has_motion()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      21, this->motion(), output);
  }

  // optional .CommonProto.OdometryFrame odometry = 22;
  if (has_odometry()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      22, this->odometry(), output);
  }

  // optional .MetaData.StructurePerception structure_perception = 30;
  if (has_structure_perception()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      30, this->structure_perception(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MetaData.Data)
}

::google::protobuf::uint8* Data::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MetaData.Data)
  // required int32 version = 1;
  if (has_version()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->version(), target);
  }

  // required int32 frame_id = 2;
  if (has_frame_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->frame_id(), target);
  }

  // repeated .CommonProto.Image image = 3;
  for (int i = 0; i < this->image_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->image(i), target);
  }

  // repeated .CommonProto.DataDescriptor data_descriptor = 4;
  for (int i = 0; i < this->data_descriptor_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->data_descriptor(i), target);
  }

  // repeated .CommonProto.CameraParam camera = 10;
  for (int i = 0; i < this->camera_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        10, this->camera(i), target);
  }

  // repeated .CommonProto.CameraParam camera_default = 11;
  for (int i = 0; i < this->camera_default_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        11, this->camera_default(i), target);
  }

  // repeated .CommonProto.CameraMatrix camera_matrix = 12;
  for (int i = 0; i < this->camera_matrix_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        12, this->camera_matrix(i), target);
  }

  // optional .MetaData.SensorFrame sensor = 20;
  if (has_sensor()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        20, this->sensor(), target);
  }

  // optional .CommonProto.MotionFrame motion = 21;
  if (has_motion()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        21, this->motion(), target);
  }

  // optional .CommonProto.OdometryFrame odometry = 22;
  if (has_odometry()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        22, this->odometry(), target);
  }

  // optional .MetaData.StructurePerception structure_perception = 30;
  if (has_structure_perception()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        30, this->structure_perception(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MetaData.Data)
  return target;
}

int Data::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 version = 1;
    if (has_version()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->version());
    }

    // required int32 frame_id = 2;
    if (has_frame_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->frame_id());
    }

    // optional .MetaData.SensorFrame sensor = 20;
    if (has_sensor()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->sensor());
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional .CommonProto.MotionFrame motion = 21;
    if (has_motion()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->motion());
    }

    // optional .CommonProto.OdometryFrame odometry = 22;
    if (has_odometry()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->odometry());
    }

    // optional .MetaData.StructurePerception structure_perception = 30;
    if (has_structure_perception()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->structure_perception());
    }

  }
  // repeated .CommonProto.Image image = 3;
  total_size += 1 * this->image_size();
  for (int i = 0; i < this->image_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->image(i));
  }

  // repeated .CommonProto.DataDescriptor data_descriptor = 4;
  total_size += 1 * this->data_descriptor_size();
  for (int i = 0; i < this->data_descriptor_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->data_descriptor(i));
  }

  // repeated .CommonProto.CameraParam camera = 10;
  total_size += 1 * this->camera_size();
  for (int i = 0; i < this->camera_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->camera(i));
  }

  // repeated .CommonProto.CameraParam camera_default = 11;
  total_size += 1 * this->camera_default_size();
  for (int i = 0; i < this->camera_default_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->camera_default(i));
  }

  // repeated .CommonProto.CameraMatrix camera_matrix = 12;
  total_size += 1 * this->camera_matrix_size();
  for (int i = 0; i < this->camera_matrix_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->camera_matrix(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Data::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Data* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Data*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Data::MergeFrom(const Data& from) {
  GOOGLE_CHECK_NE(&from, this);
  image_.MergeFrom(from.image_);
  data_descriptor_.MergeFrom(from.data_descriptor_);
  camera_.MergeFrom(from.camera_);
  camera_default_.MergeFrom(from.camera_default_);
  camera_matrix_.MergeFrom(from.camera_matrix_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_version()) {
      set_version(from.version());
    }
    if (from.has_frame_id()) {
      set_frame_id(from.frame_id());
    }
    if (from.has_sensor()) {
      mutable_sensor()->::MetaData::SensorFrame::MergeFrom(from.sensor());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_motion()) {
      mutable_motion()->::CommonProto::MotionFrame::MergeFrom(from.motion());
    }
    if (from.has_odometry()) {
      mutable_odometry()->::CommonProto::OdometryFrame::MergeFrom(from.odometry());
    }
    if (from.has_structure_perception()) {
      mutable_structure_perception()->::MetaData::StructurePerception::MergeFrom(from.structure_perception());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Data::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Data::CopyFrom(const Data& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Data::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->image())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->data_descriptor())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->camera())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->camera_default())) return false;
  if (has_sensor()) {
    if (!this->sensor().IsInitialized()) return false;
  }
  if (has_motion()) {
    if (!this->motion().IsInitialized()) return false;
  }
  if (has_odometry()) {
    if (!this->odometry().IsInitialized()) return false;
  }
  if (has_structure_perception()) {
    if (!this->structure_perception().IsInitialized()) return false;
  }
  return true;
}

void Data::Swap(Data* other) {
  if (other != this) {
    std::swap(version_, other->version_);
    std::swap(frame_id_, other->frame_id_);
    image_.Swap(&other->image_);
    data_descriptor_.Swap(&other->data_descriptor_);
    camera_.Swap(&other->camera_);
    camera_default_.Swap(&other->camera_default_);
    camera_matrix_.Swap(&other->camera_matrix_);
    std::swap(sensor_, other->sensor_);
    std::swap(motion_, other->motion_);
    std::swap(odometry_, other->odometry_);
    std::swap(structure_perception_, other->structure_perception_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Data::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Data_descriptor_;
  metadata.reflection = Data_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MetaData

// @@protoc_insertion_point(global_scope)
