// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meta_data.proto

#ifndef PROTOBUF_meta_5fdata_2eproto__INCLUDED
#define PROTOBUF_meta_5fdata_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
#include "can.pb.h"
#include "sensor.pb.h"
// @@protoc_insertion_point(includes)

namespace MetaData {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_meta_5fdata_2eproto();
void protobuf_AssignDesc_meta_5fdata_2eproto();
void protobuf_ShutdownFile_meta_5fdata_2eproto();

class Box3DResult;
class SensorFrame;
class StructurePerception;
class Data;

// ===================================================================

class Box3DResult : public ::google::protobuf::Message {
 public:
  Box3DResult();
  virtual ~Box3DResult();

  Box3DResult(const Box3DResult& from);

  inline Box3DResult& operator=(const Box3DResult& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Box3DResult& default_instance();

  void Swap(Box3DResult* other);

  // implements Message ----------------------------------------------

  Box3DResult* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Box3DResult& from);
  void MergeFrom(const Box3DResult& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required .CommonProto.Box3D box = 2;
  inline bool has_box() const;
  inline void clear_box();
  static const int kBoxFieldNumber = 2;
  inline const ::CommonProto::Box3D& box() const;
  inline ::CommonProto::Box3D* mutable_box();
  inline ::CommonProto::Box3D* release_box();
  inline void set_allocated_box(::CommonProto::Box3D* box);

  // @@protoc_insertion_point(class_scope:MetaData.Box3DResult)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_box();
  inline void clear_has_box();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::CommonProto::Box3D* box_;
  ::google::protobuf::int32 id_;
  friend void  protobuf_AddDesc_meta_5fdata_2eproto();
  friend void protobuf_AssignDesc_meta_5fdata_2eproto();
  friend void protobuf_ShutdownFile_meta_5fdata_2eproto();

  void InitAsDefaultInstance();
  static Box3DResult* default_instance_;
};
// -------------------------------------------------------------------

class SensorFrame : public ::google::protobuf::Message {
 public:
  SensorFrame();
  virtual ~SensorFrame();

  SensorFrame(const SensorFrame& from);

  inline SensorFrame& operator=(const SensorFrame& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SensorFrame& default_instance();

  void Swap(SensorFrame* other);

  // implements Message ----------------------------------------------

  SensorFrame* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SensorFrame& from);
  void MergeFrom(const SensorFrame& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .CANProto.CANFrameRaw can_frames_raw = 1;
  inline int can_frames_raw_size() const;
  inline void clear_can_frames_raw();
  static const int kCanFramesRawFieldNumber = 1;
  inline const ::CANProto::CANFrameRaw& can_frames_raw(int index) const;
  inline ::CANProto::CANFrameRaw* mutable_can_frames_raw(int index);
  inline ::CANProto::CANFrameRaw* add_can_frames_raw();
  inline const ::google::protobuf::RepeatedPtrField< ::CANProto::CANFrameRaw >&
      can_frames_raw() const;
  inline ::google::protobuf::RepeatedPtrField< ::CANProto::CANFrameRaw >*
      mutable_can_frames_raw();

  // optional .CANProto.CANFrame can_frames = 2;
  inline bool has_can_frames() const;
  inline void clear_can_frames();
  static const int kCanFramesFieldNumber = 2;
  inline const ::CANProto::CANFrame& can_frames() const;
  inline ::CANProto::CANFrame* mutable_can_frames();
  inline ::CANProto::CANFrame* release_can_frames();
  inline void set_allocated_can_frames(::CANProto::CANFrame* can_frames);

  // repeated .SensorProto.IMUFrame imu_frames_raw = 11;
  inline int imu_frames_raw_size() const;
  inline void clear_imu_frames_raw();
  static const int kImuFramesRawFieldNumber = 11;
  inline const ::SensorProto::IMUFrame& imu_frames_raw(int index) const;
  inline ::SensorProto::IMUFrame* mutable_imu_frames_raw(int index);
  inline ::SensorProto::IMUFrame* add_imu_frames_raw();
  inline const ::google::protobuf::RepeatedPtrField< ::SensorProto::IMUFrame >&
      imu_frames_raw() const;
  inline ::google::protobuf::RepeatedPtrField< ::SensorProto::IMUFrame >*
      mutable_imu_frames_raw();

  // optional .SensorProto.IMUFrame imu_frame = 12;
  inline bool has_imu_frame() const;
  inline void clear_imu_frame();
  static const int kImuFrameFieldNumber = 12;
  inline const ::SensorProto::IMUFrame& imu_frame() const;
  inline ::SensorProto::IMUFrame* mutable_imu_frame();
  inline ::SensorProto::IMUFrame* release_imu_frame();
  inline void set_allocated_imu_frame(::SensorProto::IMUFrame* imu_frame);

  // optional .SensorProto.IMUFrame imu_offset = 13;
  inline bool has_imu_offset() const;
  inline void clear_imu_offset();
  static const int kImuOffsetFieldNumber = 13;
  inline const ::SensorProto::IMUFrame& imu_offset() const;
  inline ::SensorProto::IMUFrame* mutable_imu_offset();
  inline ::SensorProto::IMUFrame* release_imu_offset();
  inline void set_allocated_imu_offset(::SensorProto::IMUFrame* imu_offset);

  // repeated .SensorProto.GPSFrameRaw gps_frames_raw = 21;
  inline int gps_frames_raw_size() const;
  inline void clear_gps_frames_raw();
  static const int kGpsFramesRawFieldNumber = 21;
  inline const ::SensorProto::GPSFrameRaw& gps_frames_raw(int index) const;
  inline ::SensorProto::GPSFrameRaw* mutable_gps_frames_raw(int index);
  inline ::SensorProto::GPSFrameRaw* add_gps_frames_raw();
  inline const ::google::protobuf::RepeatedPtrField< ::SensorProto::GPSFrameRaw >&
      gps_frames_raw() const;
  inline ::google::protobuf::RepeatedPtrField< ::SensorProto::GPSFrameRaw >*
      mutable_gps_frames_raw();

  // optional .SensorProto.GPSFrame gps_frame = 22;
  inline bool has_gps_frame() const;
  inline void clear_gps_frame();
  static const int kGpsFrameFieldNumber = 22;
  inline const ::SensorProto::GPSFrame& gps_frame() const;
  inline ::SensorProto::GPSFrame* mutable_gps_frame();
  inline ::SensorProto::GPSFrame* release_gps_frame();
  inline void set_allocated_gps_frame(::SensorProto::GPSFrame* gps_frame);

  // @@protoc_insertion_point(class_scope:MetaData.SensorFrame)
 private:
  inline void set_has_can_frames();
  inline void clear_has_can_frames();
  inline void set_has_imu_frame();
  inline void clear_has_imu_frame();
  inline void set_has_imu_offset();
  inline void clear_has_imu_offset();
  inline void set_has_gps_frame();
  inline void clear_has_gps_frame();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::CANProto::CANFrameRaw > can_frames_raw_;
  ::CANProto::CANFrame* can_frames_;
  ::google::protobuf::RepeatedPtrField< ::SensorProto::IMUFrame > imu_frames_raw_;
  ::SensorProto::IMUFrame* imu_frame_;
  ::SensorProto::IMUFrame* imu_offset_;
  ::google::protobuf::RepeatedPtrField< ::SensorProto::GPSFrameRaw > gps_frames_raw_;
  ::SensorProto::GPSFrame* gps_frame_;
  friend void  protobuf_AddDesc_meta_5fdata_2eproto();
  friend void protobuf_AssignDesc_meta_5fdata_2eproto();
  friend void protobuf_ShutdownFile_meta_5fdata_2eproto();

  void InitAsDefaultInstance();
  static SensorFrame* default_instance_;
};
// -------------------------------------------------------------------

class StructurePerception : public ::google::protobuf::Message {
 public:
  StructurePerception();
  virtual ~StructurePerception();

  StructurePerception(const StructurePerception& from);

  inline StructurePerception& operator=(const StructurePerception& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StructurePerception& default_instance();

  void Swap(StructurePerception* other);

  // implements Message ----------------------------------------------

  StructurePerception* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StructurePerception& from);
  void MergeFrom(const StructurePerception& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .CommonProto.ObstacleRaws obstacles_raws = 1;
  inline int obstacles_raws_size() const;
  inline void clear_obstacles_raws();
  static const int kObstaclesRawsFieldNumber = 1;
  inline const ::CommonProto::ObstacleRaws& obstacles_raws(int index) const;
  inline ::CommonProto::ObstacleRaws* mutable_obstacles_raws(int index);
  inline ::CommonProto::ObstacleRaws* add_obstacles_raws();
  inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::ObstacleRaws >&
      obstacles_raws() const;
  inline ::google::protobuf::RepeatedPtrField< ::CommonProto::ObstacleRaws >*
      mutable_obstacles_raws();

  // repeated .CommonProto.Obstacles obstacles = 10;
  inline int obstacles_size() const;
  inline void clear_obstacles();
  static const int kObstaclesFieldNumber = 10;
  inline const ::CommonProto::Obstacles& obstacles(int index) const;
  inline ::CommonProto::Obstacles* mutable_obstacles(int index);
  inline ::CommonProto::Obstacles* add_obstacles();
  inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::Obstacles >&
      obstacles() const;
  inline ::google::protobuf::RepeatedPtrField< ::CommonProto::Obstacles >*
      mutable_obstacles();

  // repeated .CommonProto.Lines lines = 11;
  inline int lines_size() const;
  inline void clear_lines();
  static const int kLinesFieldNumber = 11;
  inline const ::CommonProto::Lines& lines(int index) const;
  inline ::CommonProto::Lines* mutable_lines(int index);
  inline ::CommonProto::Lines* add_lines();
  inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::Lines >&
      lines() const;
  inline ::google::protobuf::RepeatedPtrField< ::CommonProto::Lines >*
      mutable_lines();

  // repeated .CommonProto.Image parsing = 20;
  inline int parsing_size() const;
  inline void clear_parsing();
  static const int kParsingFieldNumber = 20;
  inline const ::CommonProto::Image& parsing(int index) const;
  inline ::CommonProto::Image* mutable_parsing(int index);
  inline ::CommonProto::Image* add_parsing();
  inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::Image >&
      parsing() const;
  inline ::google::protobuf::RepeatedPtrField< ::CommonProto::Image >*
      mutable_parsing();

  // repeated .CommonProto.Image depth = 21;
  inline int depth_size() const;
  inline void clear_depth();
  static const int kDepthFieldNumber = 21;
  inline const ::CommonProto::Image& depth(int index) const;
  inline ::CommonProto::Image* mutable_depth(int index);
  inline ::CommonProto::Image* add_depth();
  inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::Image >&
      depth() const;
  inline ::google::protobuf::RepeatedPtrField< ::CommonProto::Image >*
      mutable_depth();

  // repeated .CommonProto.FreeSpacePoints scan_pts = 30;
  inline int scan_pts_size() const;
  inline void clear_scan_pts();
  static const int kScanPtsFieldNumber = 30;
  inline const ::CommonProto::FreeSpacePoints& scan_pts(int index) const;
  inline ::CommonProto::FreeSpacePoints* mutable_scan_pts(int index);
  inline ::CommonProto::FreeSpacePoints* add_scan_pts();
  inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::FreeSpacePoints >&
      scan_pts() const;
  inline ::google::protobuf::RepeatedPtrField< ::CommonProto::FreeSpacePoints >*
      mutable_scan_pts();

  // repeated .CommonProto.ParsingSetting parsing_settings = 40;
  inline int parsing_settings_size() const;
  inline void clear_parsing_settings();
  static const int kParsingSettingsFieldNumber = 40;
  inline const ::CommonProto::ParsingSetting& parsing_settings(int index) const;
  inline ::CommonProto::ParsingSetting* mutable_parsing_settings(int index);
  inline ::CommonProto::ParsingSetting* add_parsing_settings();
  inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::ParsingSetting >&
      parsing_settings() const;
  inline ::google::protobuf::RepeatedPtrField< ::CommonProto::ParsingSetting >*
      mutable_parsing_settings();

  // @@protoc_insertion_point(class_scope:MetaData.StructurePerception)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::CommonProto::ObstacleRaws > obstacles_raws_;
  ::google::protobuf::RepeatedPtrField< ::CommonProto::Obstacles > obstacles_;
  ::google::protobuf::RepeatedPtrField< ::CommonProto::Lines > lines_;
  ::google::protobuf::RepeatedPtrField< ::CommonProto::Image > parsing_;
  ::google::protobuf::RepeatedPtrField< ::CommonProto::Image > depth_;
  ::google::protobuf::RepeatedPtrField< ::CommonProto::FreeSpacePoints > scan_pts_;
  ::google::protobuf::RepeatedPtrField< ::CommonProto::ParsingSetting > parsing_settings_;
  friend void  protobuf_AddDesc_meta_5fdata_2eproto();
  friend void protobuf_AssignDesc_meta_5fdata_2eproto();
  friend void protobuf_ShutdownFile_meta_5fdata_2eproto();

  void InitAsDefaultInstance();
  static StructurePerception* default_instance_;
};
// -------------------------------------------------------------------

class Data : public ::google::protobuf::Message {
 public:
  Data();
  virtual ~Data();

  Data(const Data& from);

  inline Data& operator=(const Data& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Data& default_instance();

  void Swap(Data* other);

  // implements Message ----------------------------------------------

  Data* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Data& from);
  void MergeFrom(const Data& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 version = 1;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 1;
  inline ::google::protobuf::int32 version() const;
  inline void set_version(::google::protobuf::int32 value);

  // required int32 frame_id = 2;
  inline bool has_frame_id() const;
  inline void clear_frame_id();
  static const int kFrameIdFieldNumber = 2;
  inline ::google::protobuf::int32 frame_id() const;
  inline void set_frame_id(::google::protobuf::int32 value);

  // repeated .CommonProto.Image image = 3;
  inline int image_size() const;
  inline void clear_image();
  static const int kImageFieldNumber = 3;
  inline const ::CommonProto::Image& image(int index) const;
  inline ::CommonProto::Image* mutable_image(int index);
  inline ::CommonProto::Image* add_image();
  inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::Image >&
      image() const;
  inline ::google::protobuf::RepeatedPtrField< ::CommonProto::Image >*
      mutable_image();

  // repeated .CommonProto.DataDescriptor data_descriptor = 4;
  inline int data_descriptor_size() const;
  inline void clear_data_descriptor();
  static const int kDataDescriptorFieldNumber = 4;
  inline const ::CommonProto::DataDescriptor& data_descriptor(int index) const;
  inline ::CommonProto::DataDescriptor* mutable_data_descriptor(int index);
  inline ::CommonProto::DataDescriptor* add_data_descriptor();
  inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::DataDescriptor >&
      data_descriptor() const;
  inline ::google::protobuf::RepeatedPtrField< ::CommonProto::DataDescriptor >*
      mutable_data_descriptor();

  // repeated .CommonProto.CameraParam camera = 10;
  inline int camera_size() const;
  inline void clear_camera();
  static const int kCameraFieldNumber = 10;
  inline const ::CommonProto::CameraParam& camera(int index) const;
  inline ::CommonProto::CameraParam* mutable_camera(int index);
  inline ::CommonProto::CameraParam* add_camera();
  inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::CameraParam >&
      camera() const;
  inline ::google::protobuf::RepeatedPtrField< ::CommonProto::CameraParam >*
      mutable_camera();

  // repeated .CommonProto.CameraParam camera_default = 11;
  inline int camera_default_size() const;
  inline void clear_camera_default();
  static const int kCameraDefaultFieldNumber = 11;
  inline const ::CommonProto::CameraParam& camera_default(int index) const;
  inline ::CommonProto::CameraParam* mutable_camera_default(int index);
  inline ::CommonProto::CameraParam* add_camera_default();
  inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::CameraParam >&
      camera_default() const;
  inline ::google::protobuf::RepeatedPtrField< ::CommonProto::CameraParam >*
      mutable_camera_default();

  // repeated .CommonProto.CameraMatrix camera_matrix = 12;
  inline int camera_matrix_size() const;
  inline void clear_camera_matrix();
  static const int kCameraMatrixFieldNumber = 12;
  inline const ::CommonProto::CameraMatrix& camera_matrix(int index) const;
  inline ::CommonProto::CameraMatrix* mutable_camera_matrix(int index);
  inline ::CommonProto::CameraMatrix* add_camera_matrix();
  inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::CameraMatrix >&
      camera_matrix() const;
  inline ::google::protobuf::RepeatedPtrField< ::CommonProto::CameraMatrix >*
      mutable_camera_matrix();

  // optional .MetaData.SensorFrame sensor = 20;
  inline bool has_sensor() const;
  inline void clear_sensor();
  static const int kSensorFieldNumber = 20;
  inline const ::MetaData::SensorFrame& sensor() const;
  inline ::MetaData::SensorFrame* mutable_sensor();
  inline ::MetaData::SensorFrame* release_sensor();
  inline void set_allocated_sensor(::MetaData::SensorFrame* sensor);

  // optional .CommonProto.MotionFrame motion = 21;
  inline bool has_motion() const;
  inline void clear_motion();
  static const int kMotionFieldNumber = 21;
  inline const ::CommonProto::MotionFrame& motion() const;
  inline ::CommonProto::MotionFrame* mutable_motion();
  inline ::CommonProto::MotionFrame* release_motion();
  inline void set_allocated_motion(::CommonProto::MotionFrame* motion);

  // optional .CommonProto.OdometryFrame odometry = 22;
  inline bool has_odometry() const;
  inline void clear_odometry();
  static const int kOdometryFieldNumber = 22;
  inline const ::CommonProto::OdometryFrame& odometry() const;
  inline ::CommonProto::OdometryFrame* mutable_odometry();
  inline ::CommonProto::OdometryFrame* release_odometry();
  inline void set_allocated_odometry(::CommonProto::OdometryFrame* odometry);

  // optional .MetaData.StructurePerception structure_perception = 30;
  inline bool has_structure_perception() const;
  inline void clear_structure_perception();
  static const int kStructurePerceptionFieldNumber = 30;
  inline const ::MetaData::StructurePerception& structure_perception() const;
  inline ::MetaData::StructurePerception* mutable_structure_perception();
  inline ::MetaData::StructurePerception* release_structure_perception();
  inline void set_allocated_structure_perception(::MetaData::StructurePerception* structure_perception);

  // @@protoc_insertion_point(class_scope:MetaData.Data)
 private:
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_frame_id();
  inline void clear_has_frame_id();
  inline void set_has_sensor();
  inline void clear_has_sensor();
  inline void set_has_motion();
  inline void clear_has_motion();
  inline void set_has_odometry();
  inline void clear_has_odometry();
  inline void set_has_structure_perception();
  inline void clear_has_structure_perception();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 version_;
  ::google::protobuf::int32 frame_id_;
  ::google::protobuf::RepeatedPtrField< ::CommonProto::Image > image_;
  ::google::protobuf::RepeatedPtrField< ::CommonProto::DataDescriptor > data_descriptor_;
  ::google::protobuf::RepeatedPtrField< ::CommonProto::CameraParam > camera_;
  ::google::protobuf::RepeatedPtrField< ::CommonProto::CameraParam > camera_default_;
  ::google::protobuf::RepeatedPtrField< ::CommonProto::CameraMatrix > camera_matrix_;
  ::MetaData::SensorFrame* sensor_;
  ::CommonProto::MotionFrame* motion_;
  ::CommonProto::OdometryFrame* odometry_;
  ::MetaData::StructurePerception* structure_perception_;
  friend void  protobuf_AddDesc_meta_5fdata_2eproto();
  friend void protobuf_AssignDesc_meta_5fdata_2eproto();
  friend void protobuf_ShutdownFile_meta_5fdata_2eproto();

  void InitAsDefaultInstance();
  static Data* default_instance_;
};
// ===================================================================


// ===================================================================

// Box3DResult

// required int32 id = 1;
inline bool Box3DResult::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Box3DResult::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Box3DResult::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Box3DResult::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 Box3DResult::id() const {
  // @@protoc_insertion_point(field_get:MetaData.Box3DResult.id)
  return id_;
}
inline void Box3DResult::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:MetaData.Box3DResult.id)
}

// required .CommonProto.Box3D box = 2;
inline bool Box3DResult::has_box() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Box3DResult::set_has_box() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Box3DResult::clear_has_box() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Box3DResult::clear_box() {
  if (box_ != NULL) box_->::CommonProto::Box3D::Clear();
  clear_has_box();
}
inline const ::CommonProto::Box3D& Box3DResult::box() const {
  // @@protoc_insertion_point(field_get:MetaData.Box3DResult.box)
  return box_ != NULL ? *box_ : *default_instance_->box_;
}
inline ::CommonProto::Box3D* Box3DResult::mutable_box() {
  set_has_box();
  if (box_ == NULL) box_ = new ::CommonProto::Box3D;
  // @@protoc_insertion_point(field_mutable:MetaData.Box3DResult.box)
  return box_;
}
inline ::CommonProto::Box3D* Box3DResult::release_box() {
  clear_has_box();
  ::CommonProto::Box3D* temp = box_;
  box_ = NULL;
  return temp;
}
inline void Box3DResult::set_allocated_box(::CommonProto::Box3D* box) {
  delete box_;
  box_ = box;
  if (box) {
    set_has_box();
  } else {
    clear_has_box();
  }
  // @@protoc_insertion_point(field_set_allocated:MetaData.Box3DResult.box)
}

// -------------------------------------------------------------------

// SensorFrame

// repeated .CANProto.CANFrameRaw can_frames_raw = 1;
inline int SensorFrame::can_frames_raw_size() const {
  return can_frames_raw_.size();
}
inline void SensorFrame::clear_can_frames_raw() {
  can_frames_raw_.Clear();
}
inline const ::CANProto::CANFrameRaw& SensorFrame::can_frames_raw(int index) const {
  // @@protoc_insertion_point(field_get:MetaData.SensorFrame.can_frames_raw)
  return can_frames_raw_.Get(index);
}
inline ::CANProto::CANFrameRaw* SensorFrame::mutable_can_frames_raw(int index) {
  // @@protoc_insertion_point(field_mutable:MetaData.SensorFrame.can_frames_raw)
  return can_frames_raw_.Mutable(index);
}
inline ::CANProto::CANFrameRaw* SensorFrame::add_can_frames_raw() {
  // @@protoc_insertion_point(field_add:MetaData.SensorFrame.can_frames_raw)
  return can_frames_raw_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CANProto::CANFrameRaw >&
SensorFrame::can_frames_raw() const {
  // @@protoc_insertion_point(field_list:MetaData.SensorFrame.can_frames_raw)
  return can_frames_raw_;
}
inline ::google::protobuf::RepeatedPtrField< ::CANProto::CANFrameRaw >*
SensorFrame::mutable_can_frames_raw() {
  // @@protoc_insertion_point(field_mutable_list:MetaData.SensorFrame.can_frames_raw)
  return &can_frames_raw_;
}

// optional .CANProto.CANFrame can_frames = 2;
inline bool SensorFrame::has_can_frames() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SensorFrame::set_has_can_frames() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SensorFrame::clear_has_can_frames() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SensorFrame::clear_can_frames() {
  if (can_frames_ != NULL) can_frames_->::CANProto::CANFrame::Clear();
  clear_has_can_frames();
}
inline const ::CANProto::CANFrame& SensorFrame::can_frames() const {
  // @@protoc_insertion_point(field_get:MetaData.SensorFrame.can_frames)
  return can_frames_ != NULL ? *can_frames_ : *default_instance_->can_frames_;
}
inline ::CANProto::CANFrame* SensorFrame::mutable_can_frames() {
  set_has_can_frames();
  if (can_frames_ == NULL) can_frames_ = new ::CANProto::CANFrame;
  // @@protoc_insertion_point(field_mutable:MetaData.SensorFrame.can_frames)
  return can_frames_;
}
inline ::CANProto::CANFrame* SensorFrame::release_can_frames() {
  clear_has_can_frames();
  ::CANProto::CANFrame* temp = can_frames_;
  can_frames_ = NULL;
  return temp;
}
inline void SensorFrame::set_allocated_can_frames(::CANProto::CANFrame* can_frames) {
  delete can_frames_;
  can_frames_ = can_frames;
  if (can_frames) {
    set_has_can_frames();
  } else {
    clear_has_can_frames();
  }
  // @@protoc_insertion_point(field_set_allocated:MetaData.SensorFrame.can_frames)
}

// repeated .SensorProto.IMUFrame imu_frames_raw = 11;
inline int SensorFrame::imu_frames_raw_size() const {
  return imu_frames_raw_.size();
}
inline void SensorFrame::clear_imu_frames_raw() {
  imu_frames_raw_.Clear();
}
inline const ::SensorProto::IMUFrame& SensorFrame::imu_frames_raw(int index) const {
  // @@protoc_insertion_point(field_get:MetaData.SensorFrame.imu_frames_raw)
  return imu_frames_raw_.Get(index);
}
inline ::SensorProto::IMUFrame* SensorFrame::mutable_imu_frames_raw(int index) {
  // @@protoc_insertion_point(field_mutable:MetaData.SensorFrame.imu_frames_raw)
  return imu_frames_raw_.Mutable(index);
}
inline ::SensorProto::IMUFrame* SensorFrame::add_imu_frames_raw() {
  // @@protoc_insertion_point(field_add:MetaData.SensorFrame.imu_frames_raw)
  return imu_frames_raw_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SensorProto::IMUFrame >&
SensorFrame::imu_frames_raw() const {
  // @@protoc_insertion_point(field_list:MetaData.SensorFrame.imu_frames_raw)
  return imu_frames_raw_;
}
inline ::google::protobuf::RepeatedPtrField< ::SensorProto::IMUFrame >*
SensorFrame::mutable_imu_frames_raw() {
  // @@protoc_insertion_point(field_mutable_list:MetaData.SensorFrame.imu_frames_raw)
  return &imu_frames_raw_;
}

// optional .SensorProto.IMUFrame imu_frame = 12;
inline bool SensorFrame::has_imu_frame() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SensorFrame::set_has_imu_frame() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SensorFrame::clear_has_imu_frame() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SensorFrame::clear_imu_frame() {
  if (imu_frame_ != NULL) imu_frame_->::SensorProto::IMUFrame::Clear();
  clear_has_imu_frame();
}
inline const ::SensorProto::IMUFrame& SensorFrame::imu_frame() const {
  // @@protoc_insertion_point(field_get:MetaData.SensorFrame.imu_frame)
  return imu_frame_ != NULL ? *imu_frame_ : *default_instance_->imu_frame_;
}
inline ::SensorProto::IMUFrame* SensorFrame::mutable_imu_frame() {
  set_has_imu_frame();
  if (imu_frame_ == NULL) imu_frame_ = new ::SensorProto::IMUFrame;
  // @@protoc_insertion_point(field_mutable:MetaData.SensorFrame.imu_frame)
  return imu_frame_;
}
inline ::SensorProto::IMUFrame* SensorFrame::release_imu_frame() {
  clear_has_imu_frame();
  ::SensorProto::IMUFrame* temp = imu_frame_;
  imu_frame_ = NULL;
  return temp;
}
inline void SensorFrame::set_allocated_imu_frame(::SensorProto::IMUFrame* imu_frame) {
  delete imu_frame_;
  imu_frame_ = imu_frame;
  if (imu_frame) {
    set_has_imu_frame();
  } else {
    clear_has_imu_frame();
  }
  // @@protoc_insertion_point(field_set_allocated:MetaData.SensorFrame.imu_frame)
}

// optional .SensorProto.IMUFrame imu_offset = 13;
inline bool SensorFrame::has_imu_offset() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SensorFrame::set_has_imu_offset() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SensorFrame::clear_has_imu_offset() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SensorFrame::clear_imu_offset() {
  if (imu_offset_ != NULL) imu_offset_->::SensorProto::IMUFrame::Clear();
  clear_has_imu_offset();
}
inline const ::SensorProto::IMUFrame& SensorFrame::imu_offset() const {
  // @@protoc_insertion_point(field_get:MetaData.SensorFrame.imu_offset)
  return imu_offset_ != NULL ? *imu_offset_ : *default_instance_->imu_offset_;
}
inline ::SensorProto::IMUFrame* SensorFrame::mutable_imu_offset() {
  set_has_imu_offset();
  if (imu_offset_ == NULL) imu_offset_ = new ::SensorProto::IMUFrame;
  // @@protoc_insertion_point(field_mutable:MetaData.SensorFrame.imu_offset)
  return imu_offset_;
}
inline ::SensorProto::IMUFrame* SensorFrame::release_imu_offset() {
  clear_has_imu_offset();
  ::SensorProto::IMUFrame* temp = imu_offset_;
  imu_offset_ = NULL;
  return temp;
}
inline void SensorFrame::set_allocated_imu_offset(::SensorProto::IMUFrame* imu_offset) {
  delete imu_offset_;
  imu_offset_ = imu_offset;
  if (imu_offset) {
    set_has_imu_offset();
  } else {
    clear_has_imu_offset();
  }
  // @@protoc_insertion_point(field_set_allocated:MetaData.SensorFrame.imu_offset)
}

// repeated .SensorProto.GPSFrameRaw gps_frames_raw = 21;
inline int SensorFrame::gps_frames_raw_size() const {
  return gps_frames_raw_.size();
}
inline void SensorFrame::clear_gps_frames_raw() {
  gps_frames_raw_.Clear();
}
inline const ::SensorProto::GPSFrameRaw& SensorFrame::gps_frames_raw(int index) const {
  // @@protoc_insertion_point(field_get:MetaData.SensorFrame.gps_frames_raw)
  return gps_frames_raw_.Get(index);
}
inline ::SensorProto::GPSFrameRaw* SensorFrame::mutable_gps_frames_raw(int index) {
  // @@protoc_insertion_point(field_mutable:MetaData.SensorFrame.gps_frames_raw)
  return gps_frames_raw_.Mutable(index);
}
inline ::SensorProto::GPSFrameRaw* SensorFrame::add_gps_frames_raw() {
  // @@protoc_insertion_point(field_add:MetaData.SensorFrame.gps_frames_raw)
  return gps_frames_raw_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SensorProto::GPSFrameRaw >&
SensorFrame::gps_frames_raw() const {
  // @@protoc_insertion_point(field_list:MetaData.SensorFrame.gps_frames_raw)
  return gps_frames_raw_;
}
inline ::google::protobuf::RepeatedPtrField< ::SensorProto::GPSFrameRaw >*
SensorFrame::mutable_gps_frames_raw() {
  // @@protoc_insertion_point(field_mutable_list:MetaData.SensorFrame.gps_frames_raw)
  return &gps_frames_raw_;
}

// optional .SensorProto.GPSFrame gps_frame = 22;
inline bool SensorFrame::has_gps_frame() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void SensorFrame::set_has_gps_frame() {
  _has_bits_[0] |= 0x00000040u;
}
inline void SensorFrame::clear_has_gps_frame() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void SensorFrame::clear_gps_frame() {
  if (gps_frame_ != NULL) gps_frame_->::SensorProto::GPSFrame::Clear();
  clear_has_gps_frame();
}
inline const ::SensorProto::GPSFrame& SensorFrame::gps_frame() const {
  // @@protoc_insertion_point(field_get:MetaData.SensorFrame.gps_frame)
  return gps_frame_ != NULL ? *gps_frame_ : *default_instance_->gps_frame_;
}
inline ::SensorProto::GPSFrame* SensorFrame::mutable_gps_frame() {
  set_has_gps_frame();
  if (gps_frame_ == NULL) gps_frame_ = new ::SensorProto::GPSFrame;
  // @@protoc_insertion_point(field_mutable:MetaData.SensorFrame.gps_frame)
  return gps_frame_;
}
inline ::SensorProto::GPSFrame* SensorFrame::release_gps_frame() {
  clear_has_gps_frame();
  ::SensorProto::GPSFrame* temp = gps_frame_;
  gps_frame_ = NULL;
  return temp;
}
inline void SensorFrame::set_allocated_gps_frame(::SensorProto::GPSFrame* gps_frame) {
  delete gps_frame_;
  gps_frame_ = gps_frame;
  if (gps_frame) {
    set_has_gps_frame();
  } else {
    clear_has_gps_frame();
  }
  // @@protoc_insertion_point(field_set_allocated:MetaData.SensorFrame.gps_frame)
}

// -------------------------------------------------------------------

// StructurePerception

// repeated .CommonProto.ObstacleRaws obstacles_raws = 1;
inline int StructurePerception::obstacles_raws_size() const {
  return obstacles_raws_.size();
}
inline void StructurePerception::clear_obstacles_raws() {
  obstacles_raws_.Clear();
}
inline const ::CommonProto::ObstacleRaws& StructurePerception::obstacles_raws(int index) const {
  // @@protoc_insertion_point(field_get:MetaData.StructurePerception.obstacles_raws)
  return obstacles_raws_.Get(index);
}
inline ::CommonProto::ObstacleRaws* StructurePerception::mutable_obstacles_raws(int index) {
  // @@protoc_insertion_point(field_mutable:MetaData.StructurePerception.obstacles_raws)
  return obstacles_raws_.Mutable(index);
}
inline ::CommonProto::ObstacleRaws* StructurePerception::add_obstacles_raws() {
  // @@protoc_insertion_point(field_add:MetaData.StructurePerception.obstacles_raws)
  return obstacles_raws_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::ObstacleRaws >&
StructurePerception::obstacles_raws() const {
  // @@protoc_insertion_point(field_list:MetaData.StructurePerception.obstacles_raws)
  return obstacles_raws_;
}
inline ::google::protobuf::RepeatedPtrField< ::CommonProto::ObstacleRaws >*
StructurePerception::mutable_obstacles_raws() {
  // @@protoc_insertion_point(field_mutable_list:MetaData.StructurePerception.obstacles_raws)
  return &obstacles_raws_;
}

// repeated .CommonProto.Obstacles obstacles = 10;
inline int StructurePerception::obstacles_size() const {
  return obstacles_.size();
}
inline void StructurePerception::clear_obstacles() {
  obstacles_.Clear();
}
inline const ::CommonProto::Obstacles& StructurePerception::obstacles(int index) const {
  // @@protoc_insertion_point(field_get:MetaData.StructurePerception.obstacles)
  return obstacles_.Get(index);
}
inline ::CommonProto::Obstacles* StructurePerception::mutable_obstacles(int index) {
  // @@protoc_insertion_point(field_mutable:MetaData.StructurePerception.obstacles)
  return obstacles_.Mutable(index);
}
inline ::CommonProto::Obstacles* StructurePerception::add_obstacles() {
  // @@protoc_insertion_point(field_add:MetaData.StructurePerception.obstacles)
  return obstacles_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::Obstacles >&
StructurePerception::obstacles() const {
  // @@protoc_insertion_point(field_list:MetaData.StructurePerception.obstacles)
  return obstacles_;
}
inline ::google::protobuf::RepeatedPtrField< ::CommonProto::Obstacles >*
StructurePerception::mutable_obstacles() {
  // @@protoc_insertion_point(field_mutable_list:MetaData.StructurePerception.obstacles)
  return &obstacles_;
}

// repeated .CommonProto.Lines lines = 11;
inline int StructurePerception::lines_size() const {
  return lines_.size();
}
inline void StructurePerception::clear_lines() {
  lines_.Clear();
}
inline const ::CommonProto::Lines& StructurePerception::lines(int index) const {
  // @@protoc_insertion_point(field_get:MetaData.StructurePerception.lines)
  return lines_.Get(index);
}
inline ::CommonProto::Lines* StructurePerception::mutable_lines(int index) {
  // @@protoc_insertion_point(field_mutable:MetaData.StructurePerception.lines)
  return lines_.Mutable(index);
}
inline ::CommonProto::Lines* StructurePerception::add_lines() {
  // @@protoc_insertion_point(field_add:MetaData.StructurePerception.lines)
  return lines_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::Lines >&
StructurePerception::lines() const {
  // @@protoc_insertion_point(field_list:MetaData.StructurePerception.lines)
  return lines_;
}
inline ::google::protobuf::RepeatedPtrField< ::CommonProto::Lines >*
StructurePerception::mutable_lines() {
  // @@protoc_insertion_point(field_mutable_list:MetaData.StructurePerception.lines)
  return &lines_;
}

// repeated .CommonProto.Image parsing = 20;
inline int StructurePerception::parsing_size() const {
  return parsing_.size();
}
inline void StructurePerception::clear_parsing() {
  parsing_.Clear();
}
inline const ::CommonProto::Image& StructurePerception::parsing(int index) const {
  // @@protoc_insertion_point(field_get:MetaData.StructurePerception.parsing)
  return parsing_.Get(index);
}
inline ::CommonProto::Image* StructurePerception::mutable_parsing(int index) {
  // @@protoc_insertion_point(field_mutable:MetaData.StructurePerception.parsing)
  return parsing_.Mutable(index);
}
inline ::CommonProto::Image* StructurePerception::add_parsing() {
  // @@protoc_insertion_point(field_add:MetaData.StructurePerception.parsing)
  return parsing_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::Image >&
StructurePerception::parsing() const {
  // @@protoc_insertion_point(field_list:MetaData.StructurePerception.parsing)
  return parsing_;
}
inline ::google::protobuf::RepeatedPtrField< ::CommonProto::Image >*
StructurePerception::mutable_parsing() {
  // @@protoc_insertion_point(field_mutable_list:MetaData.StructurePerception.parsing)
  return &parsing_;
}

// repeated .CommonProto.Image depth = 21;
inline int StructurePerception::depth_size() const {
  return depth_.size();
}
inline void StructurePerception::clear_depth() {
  depth_.Clear();
}
inline const ::CommonProto::Image& StructurePerception::depth(int index) const {
  // @@protoc_insertion_point(field_get:MetaData.StructurePerception.depth)
  return depth_.Get(index);
}
inline ::CommonProto::Image* StructurePerception::mutable_depth(int index) {
  // @@protoc_insertion_point(field_mutable:MetaData.StructurePerception.depth)
  return depth_.Mutable(index);
}
inline ::CommonProto::Image* StructurePerception::add_depth() {
  // @@protoc_insertion_point(field_add:MetaData.StructurePerception.depth)
  return depth_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::Image >&
StructurePerception::depth() const {
  // @@protoc_insertion_point(field_list:MetaData.StructurePerception.depth)
  return depth_;
}
inline ::google::protobuf::RepeatedPtrField< ::CommonProto::Image >*
StructurePerception::mutable_depth() {
  // @@protoc_insertion_point(field_mutable_list:MetaData.StructurePerception.depth)
  return &depth_;
}

// repeated .CommonProto.FreeSpacePoints scan_pts = 30;
inline int StructurePerception::scan_pts_size() const {
  return scan_pts_.size();
}
inline void StructurePerception::clear_scan_pts() {
  scan_pts_.Clear();
}
inline const ::CommonProto::FreeSpacePoints& StructurePerception::scan_pts(int index) const {
  // @@protoc_insertion_point(field_get:MetaData.StructurePerception.scan_pts)
  return scan_pts_.Get(index);
}
inline ::CommonProto::FreeSpacePoints* StructurePerception::mutable_scan_pts(int index) {
  // @@protoc_insertion_point(field_mutable:MetaData.StructurePerception.scan_pts)
  return scan_pts_.Mutable(index);
}
inline ::CommonProto::FreeSpacePoints* StructurePerception::add_scan_pts() {
  // @@protoc_insertion_point(field_add:MetaData.StructurePerception.scan_pts)
  return scan_pts_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::FreeSpacePoints >&
StructurePerception::scan_pts() const {
  // @@protoc_insertion_point(field_list:MetaData.StructurePerception.scan_pts)
  return scan_pts_;
}
inline ::google::protobuf::RepeatedPtrField< ::CommonProto::FreeSpacePoints >*
StructurePerception::mutable_scan_pts() {
  // @@protoc_insertion_point(field_mutable_list:MetaData.StructurePerception.scan_pts)
  return &scan_pts_;
}

// repeated .CommonProto.ParsingSetting parsing_settings = 40;
inline int StructurePerception::parsing_settings_size() const {
  return parsing_settings_.size();
}
inline void StructurePerception::clear_parsing_settings() {
  parsing_settings_.Clear();
}
inline const ::CommonProto::ParsingSetting& StructurePerception::parsing_settings(int index) const {
  // @@protoc_insertion_point(field_get:MetaData.StructurePerception.parsing_settings)
  return parsing_settings_.Get(index);
}
inline ::CommonProto::ParsingSetting* StructurePerception::mutable_parsing_settings(int index) {
  // @@protoc_insertion_point(field_mutable:MetaData.StructurePerception.parsing_settings)
  return parsing_settings_.Mutable(index);
}
inline ::CommonProto::ParsingSetting* StructurePerception::add_parsing_settings() {
  // @@protoc_insertion_point(field_add:MetaData.StructurePerception.parsing_settings)
  return parsing_settings_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::ParsingSetting >&
StructurePerception::parsing_settings() const {
  // @@protoc_insertion_point(field_list:MetaData.StructurePerception.parsing_settings)
  return parsing_settings_;
}
inline ::google::protobuf::RepeatedPtrField< ::CommonProto::ParsingSetting >*
StructurePerception::mutable_parsing_settings() {
  // @@protoc_insertion_point(field_mutable_list:MetaData.StructurePerception.parsing_settings)
  return &parsing_settings_;
}

// -------------------------------------------------------------------

// Data

// required int32 version = 1;
inline bool Data::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Data::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Data::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Data::clear_version() {
  version_ = 0;
  clear_has_version();
}
inline ::google::protobuf::int32 Data::version() const {
  // @@protoc_insertion_point(field_get:MetaData.Data.version)
  return version_;
}
inline void Data::set_version(::google::protobuf::int32 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:MetaData.Data.version)
}

// required int32 frame_id = 2;
inline bool Data::has_frame_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Data::set_has_frame_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Data::clear_has_frame_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Data::clear_frame_id() {
  frame_id_ = 0;
  clear_has_frame_id();
}
inline ::google::protobuf::int32 Data::frame_id() const {
  // @@protoc_insertion_point(field_get:MetaData.Data.frame_id)
  return frame_id_;
}
inline void Data::set_frame_id(::google::protobuf::int32 value) {
  set_has_frame_id();
  frame_id_ = value;
  // @@protoc_insertion_point(field_set:MetaData.Data.frame_id)
}

// repeated .CommonProto.Image image = 3;
inline int Data::image_size() const {
  return image_.size();
}
inline void Data::clear_image() {
  image_.Clear();
}
inline const ::CommonProto::Image& Data::image(int index) const {
  // @@protoc_insertion_point(field_get:MetaData.Data.image)
  return image_.Get(index);
}
inline ::CommonProto::Image* Data::mutable_image(int index) {
  // @@protoc_insertion_point(field_mutable:MetaData.Data.image)
  return image_.Mutable(index);
}
inline ::CommonProto::Image* Data::add_image() {
  // @@protoc_insertion_point(field_add:MetaData.Data.image)
  return image_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::Image >&
Data::image() const {
  // @@protoc_insertion_point(field_list:MetaData.Data.image)
  return image_;
}
inline ::google::protobuf::RepeatedPtrField< ::CommonProto::Image >*
Data::mutable_image() {
  // @@protoc_insertion_point(field_mutable_list:MetaData.Data.image)
  return &image_;
}

// repeated .CommonProto.DataDescriptor data_descriptor = 4;
inline int Data::data_descriptor_size() const {
  return data_descriptor_.size();
}
inline void Data::clear_data_descriptor() {
  data_descriptor_.Clear();
}
inline const ::CommonProto::DataDescriptor& Data::data_descriptor(int index) const {
  // @@protoc_insertion_point(field_get:MetaData.Data.data_descriptor)
  return data_descriptor_.Get(index);
}
inline ::CommonProto::DataDescriptor* Data::mutable_data_descriptor(int index) {
  // @@protoc_insertion_point(field_mutable:MetaData.Data.data_descriptor)
  return data_descriptor_.Mutable(index);
}
inline ::CommonProto::DataDescriptor* Data::add_data_descriptor() {
  // @@protoc_insertion_point(field_add:MetaData.Data.data_descriptor)
  return data_descriptor_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::DataDescriptor >&
Data::data_descriptor() const {
  // @@protoc_insertion_point(field_list:MetaData.Data.data_descriptor)
  return data_descriptor_;
}
inline ::google::protobuf::RepeatedPtrField< ::CommonProto::DataDescriptor >*
Data::mutable_data_descriptor() {
  // @@protoc_insertion_point(field_mutable_list:MetaData.Data.data_descriptor)
  return &data_descriptor_;
}

// repeated .CommonProto.CameraParam camera = 10;
inline int Data::camera_size() const {
  return camera_.size();
}
inline void Data::clear_camera() {
  camera_.Clear();
}
inline const ::CommonProto::CameraParam& Data::camera(int index) const {
  // @@protoc_insertion_point(field_get:MetaData.Data.camera)
  return camera_.Get(index);
}
inline ::CommonProto::CameraParam* Data::mutable_camera(int index) {
  // @@protoc_insertion_point(field_mutable:MetaData.Data.camera)
  return camera_.Mutable(index);
}
inline ::CommonProto::CameraParam* Data::add_camera() {
  // @@protoc_insertion_point(field_add:MetaData.Data.camera)
  return camera_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::CameraParam >&
Data::camera() const {
  // @@protoc_insertion_point(field_list:MetaData.Data.camera)
  return camera_;
}
inline ::google::protobuf::RepeatedPtrField< ::CommonProto::CameraParam >*
Data::mutable_camera() {
  // @@protoc_insertion_point(field_mutable_list:MetaData.Data.camera)
  return &camera_;
}

// repeated .CommonProto.CameraParam camera_default = 11;
inline int Data::camera_default_size() const {
  return camera_default_.size();
}
inline void Data::clear_camera_default() {
  camera_default_.Clear();
}
inline const ::CommonProto::CameraParam& Data::camera_default(int index) const {
  // @@protoc_insertion_point(field_get:MetaData.Data.camera_default)
  return camera_default_.Get(index);
}
inline ::CommonProto::CameraParam* Data::mutable_camera_default(int index) {
  // @@protoc_insertion_point(field_mutable:MetaData.Data.camera_default)
  return camera_default_.Mutable(index);
}
inline ::CommonProto::CameraParam* Data::add_camera_default() {
  // @@protoc_insertion_point(field_add:MetaData.Data.camera_default)
  return camera_default_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::CameraParam >&
Data::camera_default() const {
  // @@protoc_insertion_point(field_list:MetaData.Data.camera_default)
  return camera_default_;
}
inline ::google::protobuf::RepeatedPtrField< ::CommonProto::CameraParam >*
Data::mutable_camera_default() {
  // @@protoc_insertion_point(field_mutable_list:MetaData.Data.camera_default)
  return &camera_default_;
}

// repeated .CommonProto.CameraMatrix camera_matrix = 12;
inline int Data::camera_matrix_size() const {
  return camera_matrix_.size();
}
inline void Data::clear_camera_matrix() {
  camera_matrix_.Clear();
}
inline const ::CommonProto::CameraMatrix& Data::camera_matrix(int index) const {
  // @@protoc_insertion_point(field_get:MetaData.Data.camera_matrix)
  return camera_matrix_.Get(index);
}
inline ::CommonProto::CameraMatrix* Data::mutable_camera_matrix(int index) {
  // @@protoc_insertion_point(field_mutable:MetaData.Data.camera_matrix)
  return camera_matrix_.Mutable(index);
}
inline ::CommonProto::CameraMatrix* Data::add_camera_matrix() {
  // @@protoc_insertion_point(field_add:MetaData.Data.camera_matrix)
  return camera_matrix_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CommonProto::CameraMatrix >&
Data::camera_matrix() const {
  // @@protoc_insertion_point(field_list:MetaData.Data.camera_matrix)
  return camera_matrix_;
}
inline ::google::protobuf::RepeatedPtrField< ::CommonProto::CameraMatrix >*
Data::mutable_camera_matrix() {
  // @@protoc_insertion_point(field_mutable_list:MetaData.Data.camera_matrix)
  return &camera_matrix_;
}

// optional .MetaData.SensorFrame sensor = 20;
inline bool Data::has_sensor() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Data::set_has_sensor() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Data::clear_has_sensor() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Data::clear_sensor() {
  if (sensor_ != NULL) sensor_->::MetaData::SensorFrame::Clear();
  clear_has_sensor();
}
inline const ::MetaData::SensorFrame& Data::sensor() const {
  // @@protoc_insertion_point(field_get:MetaData.Data.sensor)
  return sensor_ != NULL ? *sensor_ : *default_instance_->sensor_;
}
inline ::MetaData::SensorFrame* Data::mutable_sensor() {
  set_has_sensor();
  if (sensor_ == NULL) sensor_ = new ::MetaData::SensorFrame;
  // @@protoc_insertion_point(field_mutable:MetaData.Data.sensor)
  return sensor_;
}
inline ::MetaData::SensorFrame* Data::release_sensor() {
  clear_has_sensor();
  ::MetaData::SensorFrame* temp = sensor_;
  sensor_ = NULL;
  return temp;
}
inline void Data::set_allocated_sensor(::MetaData::SensorFrame* sensor) {
  delete sensor_;
  sensor_ = sensor;
  if (sensor) {
    set_has_sensor();
  } else {
    clear_has_sensor();
  }
  // @@protoc_insertion_point(field_set_allocated:MetaData.Data.sensor)
}

// optional .CommonProto.MotionFrame motion = 21;
inline bool Data::has_motion() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Data::set_has_motion() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Data::clear_has_motion() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Data::clear_motion() {
  if (motion_ != NULL) motion_->::CommonProto::MotionFrame::Clear();
  clear_has_motion();
}
inline const ::CommonProto::MotionFrame& Data::motion() const {
  // @@protoc_insertion_point(field_get:MetaData.Data.motion)
  return motion_ != NULL ? *motion_ : *default_instance_->motion_;
}
inline ::CommonProto::MotionFrame* Data::mutable_motion() {
  set_has_motion();
  if (motion_ == NULL) motion_ = new ::CommonProto::MotionFrame;
  // @@protoc_insertion_point(field_mutable:MetaData.Data.motion)
  return motion_;
}
inline ::CommonProto::MotionFrame* Data::release_motion() {
  clear_has_motion();
  ::CommonProto::MotionFrame* temp = motion_;
  motion_ = NULL;
  return temp;
}
inline void Data::set_allocated_motion(::CommonProto::MotionFrame* motion) {
  delete motion_;
  motion_ = motion;
  if (motion) {
    set_has_motion();
  } else {
    clear_has_motion();
  }
  // @@protoc_insertion_point(field_set_allocated:MetaData.Data.motion)
}

// optional .CommonProto.OdometryFrame odometry = 22;
inline bool Data::has_odometry() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Data::set_has_odometry() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Data::clear_has_odometry() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Data::clear_odometry() {
  if (odometry_ != NULL) odometry_->::CommonProto::OdometryFrame::Clear();
  clear_has_odometry();
}
inline const ::CommonProto::OdometryFrame& Data::odometry() const {
  // @@protoc_insertion_point(field_get:MetaData.Data.odometry)
  return odometry_ != NULL ? *odometry_ : *default_instance_->odometry_;
}
inline ::CommonProto::OdometryFrame* Data::mutable_odometry() {
  set_has_odometry();
  if (odometry_ == NULL) odometry_ = new ::CommonProto::OdometryFrame;
  // @@protoc_insertion_point(field_mutable:MetaData.Data.odometry)
  return odometry_;
}
inline ::CommonProto::OdometryFrame* Data::release_odometry() {
  clear_has_odometry();
  ::CommonProto::OdometryFrame* temp = odometry_;
  odometry_ = NULL;
  return temp;
}
inline void Data::set_allocated_odometry(::CommonProto::OdometryFrame* odometry) {
  delete odometry_;
  odometry_ = odometry;
  if (odometry) {
    set_has_odometry();
  } else {
    clear_has_odometry();
  }
  // @@protoc_insertion_point(field_set_allocated:MetaData.Data.odometry)
}

// optional .MetaData.StructurePerception structure_perception = 30;
inline bool Data::has_structure_perception() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void Data::set_has_structure_perception() {
  _has_bits_[0] |= 0x00000400u;
}
inline void Data::clear_has_structure_perception() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void Data::clear_structure_perception() {
  if (structure_perception_ != NULL) structure_perception_->::MetaData::StructurePerception::Clear();
  clear_has_structure_perception();
}
inline const ::MetaData::StructurePerception& Data::structure_perception() const {
  // @@protoc_insertion_point(field_get:MetaData.Data.structure_perception)
  return structure_perception_ != NULL ? *structure_perception_ : *default_instance_->structure_perception_;
}
inline ::MetaData::StructurePerception* Data::mutable_structure_perception() {
  set_has_structure_perception();
  if (structure_perception_ == NULL) structure_perception_ = new ::MetaData::StructurePerception;
  // @@protoc_insertion_point(field_mutable:MetaData.Data.structure_perception)
  return structure_perception_;
}
inline ::MetaData::StructurePerception* Data::release_structure_perception() {
  clear_has_structure_perception();
  ::MetaData::StructurePerception* temp = structure_perception_;
  structure_perception_ = NULL;
  return temp;
}
inline void Data::set_allocated_structure_perception(::MetaData::StructurePerception* structure_perception) {
  delete structure_perception_;
  structure_perception_ = structure_perception;
  if (structure_perception) {
    set_has_structure_perception();
  } else {
    clear_has_structure_perception();
  }
  // @@protoc_insertion_point(field_set_allocated:MetaData.Data.structure_perception)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MetaData

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_meta_5fdata_2eproto__INCLUDED
